// Date: 2015/08/05 19:33:38
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package jp.plusplus.ir2.blocks.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelFan extends ModelBase {
    //fields
    ModelRenderer Shape1;
    ModelRenderer Piece1;

    public ModelFan() {
        textureWidth = 64;
        textureHeight = 32;
        setTextureOffset("Piece1.Shape2", 0, 15);
        setTextureOffset("Piece1.Shape4", 0, 8);
        setTextureOffset("Piece1.Shape5", 0, 11);
        setTextureOffset("Piece1.Shape6", 0, 8);
        setTextureOffset("Piece1.Shape7", 0, 11);

        Shape1 = new ModelRenderer(this, 0, 21);
        Shape1.addBox(-1F, -8F, -1F, 2, 8, 2);
        Shape1.setRotationPoint(0F, 0F, 0F);
        Shape1.setTextureSize(64, 32);
        Shape1.mirror = true;
        setRotation(Shape1, 0F, 0F, 0F);
        Piece1 = new ModelRenderer(this, "Piece1");
        Piece1.setRotationPoint(-2F, 0F, -2F);
        setRotation(Piece1, 0F, 0F, 0F);
        Piece1.mirror = true;
        Piece1.addBox("Shape2", 0F, 0F, 0F, 4, 2, 4);
        Piece1.addBox("Shape4", 4F, 1F, 0F, 20, 1, 2);
        Piece1.addBox("Shape5", 0F, 1F, -20F, 2, 1, 20);
        Piece1.addBox("Shape6", -20F, 1F, 2F, 20, 1, 2);
        Piece1.addBox("Shape7", 2F, 1F, 4F, 2, 1, 20);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5);
        Shape1.render(f5);
    }
    public void renderBlade(float f5){
        Piece1.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
    }

}
