// Date: 2015/08/18 0:49:37
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package jp.plusplus.ir2.blocks.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import org.lwjgl.opengl.GL11;

public class ModelHarvester extends ModelBase {
    //fields
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer g1;
    ModelRenderer g2;
    ModelRenderer g3;
    ModelRenderer g4;
    ModelRenderer g5;
    ModelRenderer g6;
    ModelRenderer g7;
    ModelRenderer g8;
    ModelRenderer g9;
    ModelRenderer g10;
    ModelRenderer g11;
    ModelRenderer g12;

    public ModelHarvester() {
        textureWidth = 128;
        textureHeight = 64;

        Shape12 = new ModelRenderer(this, 0, 30);
        Shape12.addBox(-24F, 2F, -24F, 2, 3, 16);
        Shape12.setRotationPoint(0F, 0F, 0F);
        Shape12.setTextureSize(128, 64);
        Shape12.mirror = true;
        setRotation(Shape12, 0F, 0F, 0F);
        Shape13 = new ModelRenderer(this, 36, 30);
        Shape13.addBox(22F, 2F, -24F, 2, 3, 16);
        Shape13.setRotationPoint(0F, 0F, 0F);
        Shape13.setTextureSize(128, 64);
        Shape13.mirror = true;
        setRotation(Shape13, 0F, 0F, 0F);
        g1 = new ModelRenderer(this, 32, 0);
        g1.addBox(8F, -3F, -3F, 1, 7, 7);
        g1.setRotationPoint(0F, 3F, -13F);
        g1.setTextureSize(128, 64);
        g1.mirror = true;
        setRotation(g1, 0F, 0F, 0F);
        g2 = new ModelRenderer(this, 0, 0);
        g2.addBox(-22F, -3F, -3F, 1, 7, 7);
        g2.setRotationPoint(0F, 3F, -13F);
        g2.setTextureSize(128, 64);
        g2.mirror = true;
        setRotation(g2, 0F, 0F, 0F);
        g3 = new ModelRenderer(this, 16, 0);
        g3.addBox(-9F, -3F, -3F, 1, 7, 7);
        g3.setRotationPoint(0F, 3F, -13F);
        g3.setTextureSize(128, 64);
        g3.mirror = true;
        setRotation(g3, 0F, 0F, 0F);
        g4 = new ModelRenderer(this, 48, 0);
        g4.addBox(21F, -3F, -3F, 1, 7, 7);
        g4.setRotationPoint(0F, 3F, -13F);
        g4.setTextureSize(128, 64);
        g4.mirror = true;
        setRotation(g4, 0F, 0F, 0F);
        g5 = new ModelRenderer(this, 0, 28);
        g5.addBox(-22F, -2F, -4F, 44, 1, 1);
        g5.setRotationPoint(0F, 3F, -13F);
        g5.setTextureSize(128, 64);
        g5.mirror = true;
        setRotation(g5, 0F, 0F, 0F);
        g6 = new ModelRenderer(this, 0, 16);
        g6.addBox(-22F, -4F, 2F, 44, 1, 1);
        g6.setRotationPoint(0F, 3F, -13F);
        g6.setTextureSize(128, 64);
        g6.mirror = true;
        setRotation(g6, 0F, 0F, 0F);
        g7 = new ModelRenderer(this, 0, 26);
        g7.addBox(-22F, 2F, -4F, 44, 1, 1);
        g7.setRotationPoint(0F, 3F, -13F);
        g7.setTextureSize(128, 64);
        g7.mirror = true;
        setRotation(g7, 0F, 0F, 0F);
        g8 = new ModelRenderer(this, 0, 14);
        g8.addBox(-22F, -4F, -2F, 44, 1, 1);
        g8.setRotationPoint(0F, 3F, -13F);
        g8.setTextureSize(128, 64);
        g8.mirror = true;
        setRotation(g8, 0F, 0F, 0F);
        g9 = new ModelRenderer(this, 0, 18);
        g9.addBox(-22F, -2F, 4F, 44, 1, 1);
        g9.setRotationPoint(0F, 3F, -13F);
        g9.setTextureSize(128, 64);
        g9.mirror = true;
        setRotation(g9, 0F, 0F, 0F);
        g10 = new ModelRenderer(this, 0, 20);
        g10.addBox(-22F, 2F, 4F, 44, 1, 1);
        g10.setRotationPoint(0F, 3F, -13F);
        g10.setTextureSize(128, 64);
        g10.mirror = true;
        setRotation(g10, 0F, 0F, 0F);
        g11 = new ModelRenderer(this, 0, 22);
        g11.addBox(-22F, 4F, 2F, 44, 1, 1);
        g11.setRotationPoint(0F, 3F, -13F);
        g11.setTextureSize(128, 64);
        g11.mirror = true;
        setRotation(g11, 0F, 0F, 0F);
        g12 = new ModelRenderer(this, 0, 24);
        g12.addBox(-22F, 4F, -2F, 44, 1, 1);
        g12.setRotationPoint(0F, 3F, -13F);
        g12.setTextureSize(128, 64);
        g12.mirror = true;
        setRotation(g12, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5);
    }

    public void renderFrame(int length, float f5){
        for(int i=0;i<length;i++){
            Shape12.render(f5);
            Shape13.render(f5);
            GL11.glTranslatef(0, 0, -16);
        }
        GL11.glTranslatef(0,0,length*16);
    }

    public void renderWheel(float rate, float f5){
        float a=2*3.141593f*rate;

        GL11.glTranslatef(0,0,-16*rate);

        g1.rotateAngleX=a;
        g2.rotateAngleX=a;
        g3.rotateAngleX=a;
        g4.rotateAngleX=a;
        g5.rotateAngleX=a;
        g6.rotateAngleX=a;
        g7.rotateAngleX=a;
        g8.rotateAngleX=a;
        g9.rotateAngleX=a;
        g10.rotateAngleX=a;
        g11.rotateAngleX=a;
        g12.rotateAngleX=a;

        g1.render(f5);
        g2.render(f5);
        g3.render(f5);
        g4.render(f5);
        g5.render(f5);
        g6.render(f5);
        g7.render(f5);
        g8.render(f5);
        g9.render(f5);
        g10.render(f5);
        g11.render(f5);
        g12.render(f5);

        GL11.glTranslatef(0,0,16*rate);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
    }

}
