// Date: 2015/07/01 9:45:37
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package jp.plusplus.ir2.blocks.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import org.lwjgl.opengl.GL11;

public class ModelMachineSpinning extends ModelBase {
    //fields
    ModelRenderer cen2;
    ModelRenderer wheel1;
    ModelRenderer base;
    ModelRenderer carrage;
    ModelRenderer wheel4;

    public ModelMachineSpinning() {

        textureWidth = 64;
        textureHeight = 32;
        setTextureOffset("wheel1.w2", 0, 28);
        setTextureOffset("wheel1.w4", 4, 28);
        setTextureOffset("wheel1.w3", 0, 21);
        setTextureOffset("wheel1.s3", 12, 18);
        setTextureOffset("wheel1.s2", 20, 24);
        setTextureOffset("wheel1.w1", 0, 30);
        setTextureOffset("wheel1.cen", 0, 18);
        setTextureOffset("wheel1.w6", 8, 28);
        setTextureOffset("wheel1.w5", 14, 30);
        setTextureOffset("wheel1.s4", 20, 22);
        setTextureOffset("wheel1.s1", 8, 18);
        setTextureOffset("wheel1.w8", 12, 28);
        setTextureOffset("wheel1.w7", 4, 21);
        setTextureOffset("base.b2", 0, 12);
        setTextureOffset("base.b1", 0, 15);
        setTextureOffset("base.b3", 0, 0);
        setTextureOffset("base.b4", 28, 18);
        setTextureOffset("base.b5", 34, 18);
        setTextureOffset("carrage.c1", 52, 27);
        setTextureOffset("carrage.c2", 40, 27);
        setTextureOffset("carrage.spin", 24, 26);
        setTextureOffset("carrage.wheel2", 28, 29);
        setTextureOffset("carrage.wheel3", 34, 29);
        setTextureOffset("wheel4.w41", 8, 24);
        setTextureOffset("wheel4.w42", 16, 22);
        setTextureOffset("wheel4.w41", 8, 26);
        setTextureOffset("wheel4.w42", 20, 26);
        setTextureOffset("wheel4.w4c1", 16, 26);
        setTextureOffset("wheel4.w4c2", 8, 22);
        setTextureOffset("wheel4.w4c3", 12, 22);

        cen2 = new ModelRenderer(this, 50, 20);
        cen2.addBox(1F, -4F, -3F, 1, 1, 6);
        cen2.setRotationPoint(0F, 0F, 0F);
        cen2.setTextureSize(64, 32);
        cen2.mirror = true;
        setRotation(cen2, 0F, 0F, 0F);
        wheel1 = new ModelRenderer(this, "wheel1");
        wheel1.setRotationPoint(1.533333F, -7.5F, 4F);
        setRotation(wheel1, 0F, 0F, 0F);
        wheel1.mirror = true;
        wheel1.addBox("w2", 3F, -4F, 0F, 1, 1, 1);
        wheel1.addBox("w4", 3F, 3F, 0F, 1, 1, 1);
        wheel1.addBox("w3", 4F, -3F, 0F, 1, 6, 1);
        wheel1.addBox("s3", -1F, 1F, 0F, 1, 3, 1);
        wheel1.addBox("s2", 1F, 0F, 0F, 3, 1, 1);
        wheel1.addBox("w1", -3F, -5F, 0F, 6, 1, 1);
        wheel1.addBox("cen", -1F, -1F, 0F, 2, 2, 1);
        wheel1.addBox("w6", -4F, 3F, 0F, 1, 1, 1);
        wheel1.addBox("w5", -3F, 4F, 0F, 6, 1, 1);
        wheel1.addBox("s4", -4F, -1F, 0F, 3, 1, 1);
        wheel1.addBox("s1", 0F, -4F, 0F, 1, 3, 1);
        wheel1.addBox("w8", -4F, -4F, 0F, 1, 1, 1);
        wheel1.addBox("w7", -5F, -3F, 0F, 1, 6, 1);
        base = new ModelRenderer(this, "base");
        base.setRotationPoint(1F, -8F, 4F);
        setRotation(base, 0F, 0F, 0F);
        base.mirror = false;
        base.addBox("b2", -8F, 0F, 1F, 30, 2, 1);
        base.addBox("b1", -8F, 4F, -1F, 30, 2, 1);
        base.addBox("b3", -8F, 10F, -8F, 30, 1, 11);
        base.addBox("b4", -8F, 0F, 0F, 2, 10, 1);
        base.addBox("b5", 20F, 0F, 0F, 2, 10, 1);
        carrage = new ModelRenderer(this, "carrage");
        carrage.setRotationPoint(19F, -4F, -1F);
        setRotation(carrage, 0F, 0F, 0F);
        carrage.mirror = false;
        carrage.addBox("c1", 0F, 0F, -1F, 1, 1, 4);
        carrage.addBox("c2", -0.5F, 4F, -1F, 2, 1, 4);
        carrage.addBox("spin", 0F, 1F, 0.5F, 1, 3, 1);
        carrage.addBox("wheel2", -0.5F, 4F, -2F, 2, 2, 1);
        carrage.addBox("wheel3", -0.5F, 4F, 3F, 2, 2, 1);
        wheel4 = new ModelRenderer(this, "wheel4");
        wheel4.setRotationPoint(-4F, -3F, 2F);
        setRotation(wheel4, 0F, 0F, 0F);
        wheel4.mirror = true;
        wheel4.addBox("w41", -1.5F, 1.5F, 0F, 3, 1, 1);
        wheel4.addBox("w42", 1.5F, -1.5F, 0F, 1, 3, 1);
        wheel4.addBox("w41", -1.5F, -2.5F, 0F, 3, 1, 1);
        wheel4.addBox("w42", -2.5F, -1.5F, 0F, 1, 3, 1);
        wheel4.addBox("w4c1", -0.5F, -1.5F, 0F, 1, 3, 1);
        wheel4.addBox("w4c2", -1.5F, -0.5F, 0F, 1, 1, 1);
        wheel4.addBox("w4c3", 0.5F, -0.5F, 0F, 1, 1, 1);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5);
        cen2.render(f5);
        base.render(f5);
    }
    public void renderWheel(float rate, float f5){
        //GL11.glRotatef(20*360*rate, 0,0,1);
        setRotation(wheel1, 0,0,rate);
        setRotation(wheel4, 0,0,rate);
        wheel1.render(f5);
        wheel4.render(f5);
    }
    public void renderCarrage(float rate, float f5) {
        float tf = 0;

        //計4回動かす
        while(rate>=0.25f) rate-=0.25f;
        rate/=0.25f;

        if (rate < 0.3f) tf = -rate / 0.3f;
        else if (rate < 0.4f) tf = -1f - 15f * (rate - 0.3f) / 0.1f;
        else if (rate < 0.6f) tf = -16f + 1f * (rate - 0.4f) / 0.2f;
        else if (rate < 0.8f) tf = -15f - 1f * (rate - 0.6f) / 0.2f;
        else tf = (-16f) * (1.0f - (rate - 0.8f) / 0.2f);

        GL11.glTranslatef(tf, 0, 0);
        carrage.render(f5);
        GL11.glTranslatef(-tf, 0, 0);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
    }

}
