// Date: 2015/08/17 9:22:02
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package jp.plusplus.ir2.blocks.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelPump extends ModelBase {
    //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Lever0;
    ModelRenderer Lever1;
    ModelRenderer Lever2;

    public ModelPump() {
        textureWidth = 64;
        textureHeight = 32;

        Shape1 = new ModelRenderer(this, 4, 2);
        Shape1.addBox(2F, -10F, -1F, 1, 3, 2);
        Shape1.setRotationPoint(0F, 0F, 0F);
        Shape1.setTextureSize(64, 32);
        Shape1.mirror = true;
        setRotation(Shape1, 0F, 0F, 0F);
        Shape2 = new ModelRenderer(this, 10, 0);
        Shape2.addBox(-3F, -2F, -3F, 6, 2, 6);
        Shape2.setRotationPoint(0F, 0F, 0F);
        Shape2.setTextureSize(64, 32);
        Shape2.mirror = true;
        setRotation(Shape2, 0F, 0F, 0F);
        Shape3 = new ModelRenderer(this, 0, 9);
        Shape3.addBox(-1F, -6F, -1F, 2, 4, 2);
        Shape3.setRotationPoint(0F, 0F, 0F);
        Shape3.setTextureSize(64, 32);
        Shape3.mirror = true;
        setRotation(Shape3, 0F, 0F, 0F);
        Shape4 = new ModelRenderer(this, 8, 8);
        Shape4.addBox(-2F, -9F, -2F, 4, 3, 4);
        Shape4.setRotationPoint(0F, 0F, 0F);
        Shape4.setTextureSize(64, 32);
        Shape4.mirror = true;
        setRotation(Shape4, 0F, 0F, 0F);
        Lever0 = new ModelRenderer(this, 0, 0);
        Lever0.addBox(-3F, -0.5F, 0F, 6, 1, 1);
        Lever0.setRotationPoint(2.5F, -10.5F, -0.5F);
        Lever0.setTextureSize(64, 32);
        Lever0.mirror = true;
        setRotation(Lever0, 0F, 0F, 0F);
        Lever1 = new ModelRenderer(this, 0, 2);
        Lever1.addBox(2F, 0.5F, -0.5F, 1, 4, 1);
        Lever1.setRotationPoint(2.5F, -10.5F, 0F);
        Lever1.setTextureSize(64, 32);
        Lever1.mirror = true;
        setRotation(Lever1, 0F, 0F, 0F);
        Lever2 = new ModelRenderer(this, 0, 7);
        Lever2.addBox(2F, 4.5F, -0.5F, 3, 1, 1);
        Lever2.setRotationPoint(2.5F, -10.5F, 0F);
        Lever2.setTextureSize(64, 32);
        Lever2.mirror = true;
        setRotation(Lever2, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5);
        Shape1.render(f5);
        Shape2.render(f5);
        Shape3.render(f5);
        Shape4.render(f5);
    }

    public void renderLever(float rate, float f5){
        // 0-30dの範囲を
        float a=0.5f*0.334f*3.141593f* MathHelper.sin(3.141593f*rate);

        Lever0.rotateAngleZ=a;
        Lever1.rotateAngleZ=a;
        Lever2.rotateAngleZ=a;

        Lever0.render(f5);
        Lever1.render(f5);
        Lever2.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
    }

}
