// Date: 2015/07/04 12:01:13
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package jp.plusplus.ir2.blocks.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import org.lwjgl.opengl.GL11;

public class ModelCrusher extends ModelBase {

    //fields
    ModelRenderer g1;
    ModelRenderer g2;
    ModelRenderer g3;
    ModelRenderer g4;
    ModelRenderer g5;
    ModelRenderer g6;
    ModelRenderer g7;
    ModelRenderer g8;
    ModelRenderer g1b;
    ModelRenderer g2b;
    ModelRenderer g3b;
    ModelRenderer g4b;
    ModelRenderer g5b;
    ModelRenderer g6b;
    ModelRenderer g7b;
    ModelRenderer g8b;
    ModelRenderer belt;
    ModelRenderer casing1;
    ModelRenderer casing3;
    ModelRenderer casing2;
    ModelRenderer casing5;
    ModelRenderer casing4;
    ModelRenderer strage;
    ModelRenderer b1;
    ModelRenderer b2;
    ModelRenderer b3;
    ModelRenderer b4;
    ModelRenderer b5;
    ModelRenderer b6;
    ModelRenderer b7;
    ModelRenderer b8;

    public ModelCrusher() {
        textureWidth = 64;
        textureHeight = 32;

        g1 = new ModelRenderer(this, 32, 17);
        g1.addBox(-1F, 1.5F, 0F, 2, 1, 14);
        g1.setRotationPoint(-3f, -10F, -7f);
        g1.setTextureSize(64, 32);
        g1.mirror = true;
        setRotation(g1, 0F, 0F, 0F);
        g2 = new ModelRenderer(this, 32, 17);
        g2.addBox(-1.033333F, 1.5F, 0F, 2, 1, 14);
        g2.setRotationPoint(-3f, -10F, -7f);
        g2.setTextureSize(64, 32);
        g2.mirror = true;
        setRotation(g2, 0F, 0F, 0.7853982F);
        g3 = new ModelRenderer(this, 18, 15);
        g3.addBox(-2.5F, -1F, 0F, 1, 2, 14);
        g3.setRotationPoint(-3f, -10F, -7f);
        g3.setTextureSize(64, 32);
        g3.mirror = true;
        setRotation(g3, 0F, 0F, 0F);
        g4 = new ModelRenderer(this, 32, 17);
        g4.addBox(-1F, -2.5F, 0F, 2, 1, 14);
        g4.setRotationPoint(-3f, -10F, -7f);
        g4.setTextureSize(64, 32);
        g4.mirror = true;
        setRotation(g4, 0F, 0F, -0.7853982F);
        g5 = new ModelRenderer(this, 32, 17);
        g5.addBox(-1F, -2.5F, 0F, 2, 1, 14);
        g5.setRotationPoint(-3f, -10F, -7f);
        g5.setTextureSize(64, 32);
        g5.mirror = true;
        setRotation(g5, 0F, 0F, 0F);
        g6 = new ModelRenderer(this, 32, 17);
        g6.addBox(-1F, -2.5F, 0F, 2, 1, 14);
        g6.setRotationPoint(-3f, -10F, -7f);
        g6.setTextureSize(64, 32);
        g6.mirror = true;
        setRotation(g6, 0F, 0F, 0.7853982F);
        g7 = new ModelRenderer(this, 18, 15);
        g7.addBox(1.5F, -1F, 0F, 1, 2, 14);
        g7.setRotationPoint(-3f, -10F, -7f);
        g7.setTextureSize(64, 32);
        g7.mirror = true;
        setRotation(g7, 0F, 0F, 0F);
        g8 = new ModelRenderer(this, 32, 17);
        g8.addBox(-1F, 1.5F, 0F, 2, 1, 14);
        g8.setRotationPoint(-3f, -10F, -7f);
        g8.setTextureSize(64, 32);
        g8.mirror = true;
        setRotation(g8, 0F, 0F, -0.7853982F);
        g1b = new ModelRenderer(this, 32, 17);
        g1b.addBox(-1F, 1.5F, 0F, 2, 1, 14);
        g1b.setRotationPoint(3f, -10F, -7f);
        g1b.setTextureSize(64, 32);
        g1b.mirror = true;
        setRotation(g1b, 0F, 0F, 0F);
        g2b = new ModelRenderer(this, 32, 17);
        g2b.addBox(-1F, 1.5F, 0F, 2, 1, 14);
        g2b.setRotationPoint(3f, -10F, -7f);
        g2b.setTextureSize(64, 32);
        g2b.mirror = true;
        setRotation(g2b, 0F, 0F, 0.7853982F);
        g3b = new ModelRenderer(this, 18, 15);
        g3b.addBox(-2.5F, -1F, 0F, 1, 2, 14);
        g3b.setRotationPoint(3f, -10F, -7f);
        g3b.setTextureSize(64, 32);
        g3b.mirror = true;
        setRotation(g3b, 0F, 0F, 0F);
        g4b = new ModelRenderer(this, 32, 17);
        g4b.addBox(-1F, -2.5F, 0F, 2, 1, 14);
        g4b.setRotationPoint(3f, -10F, -7f);
        g4b.setTextureSize(64, 32);
        g4b.mirror = true;
        setRotation(g4b, 0F, 0F, -0.7853982F);
        g5b = new ModelRenderer(this, 32, 17);
        g5b.addBox(-1F, -2.5F, 0F, 2, 1, 14);
        g5b.setRotationPoint(3f, -10F, -7f);
        g5b.setTextureSize(64, 32);
        g5b.mirror = true;
        setRotation(g5b, 0F, 0F, 0F);
        g6b = new ModelRenderer(this, 32, 17);
        g6b.addBox(-1F, -2.5F, 0F, 2, 1, 14);
        g6b.setRotationPoint(3f, -10F, -7f);
        g6b.setTextureSize(64, 32);
        g6b.mirror = true;
        setRotation(g6b, 0F, 0F, 0.7853982F);
        g7b = new ModelRenderer(this, 18, 15);
        g7b.addBox(1.5F, -1F, 0F, 1, 2, 14);
        g7b.setRotationPoint(3f, -10F, -7f);
        g7b.setTextureSize(64, 32);
        g7b.mirror = true;
        setRotation(g7b, 0F, 0F, 0F);
        g8b = new ModelRenderer(this, 32, 17);
        g8b.addBox(-1F, 1.5F, 0F, 2, 1, 14);
        g8b.setRotationPoint(3f, -10F, -7f);
        g8b.setTextureSize(64, 32);
        g8b.mirror = true;
        setRotation(g8b, 0F, 0F, -0.7853982F);
        belt = new ModelRenderer(this, 6, 18);
        belt.addBox(0F, -2.5F, 1F, 22, 0, 14);
        belt.setRotationPoint(-7f, 0F, -8f);
        belt.setTextureSize(64, 32);
        belt.mirror = true;
        setRotation(belt, 0F, 0F, 0.0698132F);
        casing1 = new ModelRenderer(this, 0, 11);
        casing1.addBox(0F, -7F, 0F, 12, 7, 1);
        casing1.setRotationPoint(-8f, 0F, -8f);
        casing1.setTextureSize(64, 32);
        casing1.mirror = true;
        setRotation(casing1, 0F, 0F, 0F);
        casing3 = new ModelRenderer(this, 0, 11);
        casing3.addBox(0F, -7F, 15F, 12, 7, 1);
        casing3.setRotationPoint(-8f, 0F, -8f);
        casing3.setTextureSize(64, 32);
        casing3.mirror = true;
        setRotation(casing3, 0F, 0F, 0F);
        casing2 = new ModelRenderer(this, 35, 2);
        casing2.addBox(0F, -7F, 1F, 1, 7, 14);
        casing2.setRotationPoint(-8f, 0F, -8f);
        casing2.setTextureSize(64, 32);
        casing2.mirror = true;
        setRotation(casing2, 0F, 0F, 0F);
        casing5 = new ModelRenderer(this, 0, 19);
        casing5.addBox(12F, -3F, 0F, 11, 3, 1);
        casing5.setRotationPoint(-8f, 0F, -8f);
        casing5.setTextureSize(64, 32);
        casing5.mirror = true;
        setRotation(casing5, 0F, 0F, 0F);
        casing4 = new ModelRenderer(this, 0, 19);
        casing4.addBox(12F, -3F, 15F, 11, 3, 1);
        casing4.setRotationPoint(-8f, 0F, -8f);
        casing4.setTextureSize(64, 32);
        casing4.mirror = true;
        setRotation(casing4, 0F, 0F, 0F);
        strage = new ModelRenderer(this, 0, 7);
        strage.addBox(23F, -9F, 0F, 9, 9, 16);
        strage.setRotationPoint(-8f, 0F, -8f);
        strage.setTextureSize(64, 32);
        strage.mirror = true;
        setRotation(strage, 0F, 0F, 0F);
        b1 = new ModelRenderer(this, 0, 0);
        b1.addBox(0F, -12F, 0F, 16, 5, 1);
        b1.setRotationPoint(-8f, 0F, -8f);
        b1.setTextureSize(64, 32);
        b1.mirror = true;
        setRotation(b1, 0F, 0F, 0F);
        b2 = new ModelRenderer(this, 34, 4);
        b2.addBox(0F, -12F, 1F, 1, 5, 14);
        b2.setRotationPoint(-8f, 0F, -8f);
        b2.setTextureSize(64, 32);
        b2.mirror = true;
        setRotation(b2, 0F, 0F, 0F);
        b3 = new ModelRenderer(this, 0, 0);
        b3.addBox(0F, -12F, 15F, 16, 5, 1);
        b3.setRotationPoint(-8f, 0F, -8f);
        b3.setTextureSize(64, 32);
        b3.mirror = true;
        setRotation(b3, 0F, 0F, 0F);
        b4 = new ModelRenderer(this, 34, 4);
        b4.addBox(15F, -12F, 1F, 1, 5, 14);
        b4.setRotationPoint(-8f, 0F, -8f);
        b4.setTextureSize(64, 32);
        b4.mirror = true;
        setRotation(b4, 0F, 0F, 0F);
        b5 = new ModelRenderer(this, 34, 0);
        b5.addBox(1F, -7F, 1F, 14, 3, 1);
        b5.setRotationPoint(-8f, 0F, -8f);
        b5.setTextureSize(64, 32);
        b5.mirror = true;
        setRotation(b5, 0F, 0F, 0F);
        b6 = new ModelRenderer(this, 38, 0);
        b6.addBox(1F, -7F, 2F, 1, 3, 12);
        b6.setRotationPoint(-8f, 0F, -8f);
        b6.setTextureSize(64, 32);
        b6.mirror = true;
        setRotation(b6, 0F, 0F, 0F);
        b7 = new ModelRenderer(this, 34, 0);
        b7.addBox(1F, -7F, 14F, 14, 3, 1);
        b7.setRotationPoint(-8f, 0F, -8f);
        b7.setTextureSize(64, 32);
        b7.mirror = true;
        setRotation(b7, 0F, 0F, 0F);
        b8 = new ModelRenderer(this, 38, 0);
        b8.addBox(14F, -7F, 2F, 1, 3, 12);
        b8.setRotationPoint(-8f, 0F, -8f);
        b8.setTextureSize(64, 32);
        b8.mirror = true;
        setRotation(b8, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5);
    }
    public void renderGear(float rate, float f5){
        float angle=8*360.0f*rate;

        //GL11.glRotatef(angle, 0,0,1);
        g1.rotateAngleZ=angle;
        g2.rotateAngleZ=angle+45;
        g3.rotateAngleZ=angle;
        g4.rotateAngleZ=angle-45;
        g5.rotateAngleZ=angle;
        g6.rotateAngleZ=angle+45;
        g7.rotateAngleZ=angle;
        g8.rotateAngleZ=angle-45;
        g1.render(f5);
        g2.render(f5);
        g3.render(f5);
        g4.render(f5);
        g5.render(f5);
        g6.render(f5);
        g7.render(f5);
        g8.render(f5);

        //GL11.glRotatef(-2*angle, 0,0,1);
        angle=-angle;
        g1b.rotateAngleZ=angle;
        g2b.rotateAngleZ=angle+45;
        g3b.rotateAngleZ=angle;
        g4b.rotateAngleZ=angle-45;
        g5b.rotateAngleZ=angle;
        g6b.rotateAngleZ=angle+45;
        g7b.rotateAngleZ=angle;
        g8b.rotateAngleZ=angle-45;
        g1b.render(f5);
        g2b.render(f5);
        g3b.render(f5);
        g4b.render(f5);
        g5b.render(f5);
        g6b.render(f5);
        g7b.render(f5);
        g8b.render(f5);
    }
    public void renderCasing(float f5){
        casing1.render(f5);
        casing3.render(f5);
        casing2.render(f5);
        casing5.render(f5);
        casing4.render(f5);
    }
    public void renderBelt(float f5){
        belt.render(f5);
    }
    public void renderBox(float f5){
        strage.render(f5);
        b1.render(f5);
        b2.render(f5);
        b3.render(f5);
        b4.render(f5);
        b5.render(f5);
        b6.render(f5);
        b7.render(f5);
        b8.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
    }
}
